print("Official Rating System 2020")
print("Rate T&A From 1-10")
print("*Bigger is not necessarily better")
T = int(input())
print("Rate Face From 1-10")
print("*You can't fix ugly")
F = int(input())
print("What is her body count?")
print("*Hoes Mad")
B = int(input())
print("Does she have a nose ring?")
print("*Insert 1 if yes, 0 if no")
N = int(input())
print("Approximately how many square inches of tattoos does she have?")
print("Round to the nearest inch")
O = int(input())
print("Is she psycho?")
print("Insert 1 if yes, 0 if no")
P = int(input())
print("How much does she weigh?")
print("Use Pounds")
M = int(input())
print("how many feet tall is she?")
print("*Round down to the foot")
Height = input()
H = int(Height)
print("How many inches above " + Height + " feet is she?")
print("Round to the nearest inch")
I = int(input())
BMI = (M*0.453592/(((H*12+I)*0.0254)**2))
print("The Final Rating is")
if BMI<18:
	print((T*0.5+F*0.5)*(0.9**B)*(0.8**N)*(0.9**(O/9))*(0.8**P)*(0.9**(18-BMI)))
elif BMI>23: 
	print((T*0.5+F*0.5)*(0.9**B)*(0.8**N)*(0.9**(O/9))*(0.8**P)*(0.9**(BMI-23)))
else:
	print((T*0.5+F*0.5)*(0.9**B)*(0.8**N)*(0.9**(O/9))*(0.8**P))